### ISSUE TITLE
TypeError: PuppeteerScreenRecorder is not a constructor using commonJS require statement

### ISSUE THREAD

**Issue by patrickdundas** [prasanaworld/puppeteer-screen-recorder#4]
- **I'm submitting a ...**
  [x] bug report

- **Summary**

When running the example code, I get the following error:

```
> node render_recorder.js
(node:80236) UnhandledPromiseRejectionWarning: TypeError: PuppeteerScreenRecorder is not a constructor
    at /Users/Patrick.Dundas/git/critical-css-generator/generator/render_recorder.js:7:20
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:80236) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:80236) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Here is my code:

```
const puppeteer = require('puppeteer');
const PuppeteerScreenRecorder = require('puppeteer-screen-recorder');

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  const recorder = new PuppeteerScreenRecorder(page);
  await recorder.start('./report/video/simple.mp4'); // video must have .mp4 has an extension.
  await page.goto('https://example.com');

  await page.goto('https://test.com');
  await recorder.stop();
  await browser.close();
})();
```

Node version: 14.15.1 
Project version from NPM: 1.1.6
OS: MacOS

**Comment by patrickdundas** [comment]
It looks like using:
```
  const recorder = new PuppeteerScreenRecorder.PuppeteerScreenRecorder(page);
```
Fixes the issue. Example code should be updated

**Comment by prasanaworld** [comment]
Hello Patcikdundas,

Thanks for reaching out. All our codes are migrated to typescript (with Es7 support). so I haven't updated the example of late.    


As you noted, you could use it that way, But I would recommend you to have the following piece of code for better readability.

instead of  using 

```
  const recorder = new PuppeteerScreenRecorder.PuppeteerScreenRecorder(page);
 ```

change your import to
```
const { PuppeteerScreenRecorder } = require('puppeteer-screen-recorder');
```

```
const puppeteer = require('puppeteer');
const { PuppeteerScreenRecorder } = require('puppeteer-screen-recorder');

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  const recorder = new PuppeteerScreenRecorder(page);
  await recorder.start('./report/video/simple.mp4'); // video must have .mp4 has an extension.
  await page.goto('https://example.com');

  await page.goto('https://test.com');
  await recorder.stop();
  await browser.close();
})();
```

I'll also update the document shortly.
